#!/usr/bin/env bash
#
# Bench procedure runner: the agent runs this script; the operator follows the
# prompts at the bench. Generated by the armature-bringup skill. Bash only
# (Git Bash on Windows).
#
# Everything above the STAGES marker is the runner library — identical in
# every procedure; never hand-edit it. Author the stages below the marker.
#
# Helpers (step/confirm/capture keep the contract of the plugin's
# scripts/human-loop.template.sh):
#   stage "<name>"            clear the screen, announce stage N of TOTAL_STAGES
#   say / note / warn "<line>" plain / dim / flagged context under the stage
#   step "<instruction>"      show an instruction, wait for Enter
#   confirm "<gate>"          require exactly "y" to continue; anything else
#                             aborts the run, and the abort is recorded
#   capture VAR "<question>"  read the operator's answer into VAR; every value
#                             lands in the report's Data section and prints as
#                             KEY=VALUE at the end, where the agent reads it

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Runner library
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""
fi

# Author sets these at the top of the stages section.
TEST_ID=""; TEST_NAME=""; REPORT=""; TOTAL_STAGES=0

_STAGE_INDEX=0
CAPTURED=()
RUN_STATUS="in progress"

# _clear wipes the terminal so only the current stage is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  Test %s · %s%s\n' "$BOLD" "$BLUE" "$TEST_ID" "$TEST_NAME" "$RESET"
  printf '%s  %s stages · report: %s%s\n\n' "$DIM" "$TOTAL_STAGES" "$REPORT" "$RESET"
  printf '%s  You drive the bench; this runner says exactly what to do and records\n' "$DIM"
  printf '  what you measure. Ctrl-C or a failed gate aborts the run, and the\n'
  printf '  abort is recorded too.%s\n\n' "$RESET"
  read -r -p "  Ready to start? [Enter] " _ || true
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

step() {
  printf '\n  >>> %s\n' "$1"
  read -r -p "      [Enter when done] " _
}

confirm() {
  local answer
  printf '\n  %s>>> GATE: %s%s\n' "$YELLOW" "$1" "$RESET"
  read -r -p "      [y to proceed, anything else aborts] " answer
  if [[ "${answer}" != "y" ]]; then
    RUN_STATUS="aborted at gate: $1"
    printf '  ABORTED at gate: %s\n' "$1"
    exit 1
  fi
}

capture() {
  local var="$1" question="$2" answer
  printf '\n  >>> %s\n' "$question"
  read -r -p "      > " answer
  printf -v "$var" '%s' "$answer"
  CAPTURED+=("$var")
}

# _flush appends this run to the report (creating the skeleton on first run)
# and prints every captured value as KEY=VALUE for the agent. Runs on every
# exit — completed or aborted — once a stage has been entered.
_flush() {
  (( _STAGE_INDEX > 0 )) || return 0
  if [[ ! -f "$REPORT" ]]; then
    mkdir -p "$(dirname "$REPORT")"
    {
      printf '# Test %s: %s\n\n' "$TEST_ID" "$TEST_NAME"
      printf '**Purpose:** <REQ-xxx or kill criterion>\n\n'
      printf '## Setup\n\n<hardware, fixtures, instruments with resolution, environment>\n\n'
      printf '## Method\n\nRun `%s`; its stages are the numbered steps.\n\n' "$0"
      printf '## Data\n'
    } > "$REPORT"
  fi
  {
    printf '\n### Run %s — %s\n\n' "$(date '+%Y-%m-%d %H:%M')" "$RUN_STATUS"
    for var in ${CAPTURED[@]+"${CAPTURED[@]}"}; do
      printf -- '- %s: %s\n' "$var" "${!var}"
    done
  } >> "$REPORT"
  printf '\n--- Captured (%s) ---\n' "$RUN_STATUS"
  for var in ${CAPTURED[@]+"${CAPTURED[@]}"}; do
    printf '%s=%s\n' "$var" "${!var}"
  done
  printf 'REPORT=%s\n' "$REPORT"
}
trap _flush EXIT

finish() {
  RUN_STATUS="completed"
  _clear
  printf '\n%s%s  ✓ Test %s complete%s\n' "$BOLD" "$GREEN" "$TEST_ID" "$RESET"
  note "run recorded in $REPORT — Result and Feeds still to fill in"
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. Replace the example; set the four values.
# ──────────────────────────────────────────────────────────────────────────

TEST_ID="T-00"
TEST_NAME="Example: joint 2 first motion"
REPORT="docs/testing/T-00-report.md"
TOTAL_STAGES=3

banner

# ── Example stages: replace with the plan task's real steps ───────────────
stage "Bench safety"
confirm "Bench supply current-limited and e-stop in reach?"

stage "First power-on"
say "First power-on since the rework — watch the current display."
step "Connect the bench supply to the main bus."
capture IDLE_CURRENT "Idle bus current, from the supply display (A):"

stage "First motion"
confirm "Everyone clear of the arm's envelope?"
step "Enable joint 2 and command 30 deg."
capture MOVE_CURRENT "Peak bus current during the move, from the supply display (A):"
capture FAULT_LED "Did the fault LED latch? (y/n)"
# ──────────────────────────────────────────────────────────────────────────

finish
